### ISSUE TITLE
BetterEconomy

### ISSUE THREAD

**Issue by Yomamaeatstoes** [HSGamer/BetterEconomy#65]
Please make it so you can disable the auto save feature

**Comment by HSGamer** [comment]
I can add that but...
If your server crashes and the money is not saved, then don't bug me on why it's not saved.
That's why I didn't add an option for that.

**Comment by Yomamaeatstoes** [comment]
Makes sense ( :

**Comment by Yomamaeatstoes** [comment]
Thank you for adding this <3
