### ISSUE TITLE
PLACEHOLDER API

### ISSUE THREAD

**Issue by chelminski** [HSGamer/BetterEconomy#88]
Hi ;)
I'm writing to suggest new features that seem insanely important to me!

- Please add PlaceholderAPI support for Top Balance. Unfortunately, Vault does not support this feature.
- Also, please add a function to automatically clear funds from the user's account when he does not log in for X days.

Could you start a Discord channel? Many people would certainly be interested in joining the community (which is constantly growing). Your plugin is really good. You could, for example, provide help only for donors ;).

**Comment by HSGamer** [comment]
I already made a Discord server.
If you are from the Spigot page, read the Notice.

**Comment by HSGamer** [comment]
> * Also, please add a function to automatically clear funds from the user's account when he does not log in for X days.

I won't add this because it's against the goal. It is not useful for every servers.

**Comment by chelminski** [comment]
I was more about adding this feature + the ability to customize in config.
enable: true/false
days: <number>

**Comment by HSGamer** [comment]
I'm still against it. It's not worth adding a new task as most servers would just disable it.
It's more like a custom plugin to me. A plugin that runs actions when the player is offline for a specific days.
