### ISSUE TITLE
Money transaction response issue

### ISSUE THREAD

**Issue by housemazter** [HSGamer/BetterEconomy#98]
Hi
Thank you for your great plugin!
Please can you help with issue in transaction.
So, we have SkyBlock plugin (BG-Software-LLC/SuperiorSkyblock2) and we found serious issue with money transactions.
Money charge working, but transaction failed.
When we tried to move money from player to Island deposit. 
They plugin said: "Error | Successful." and transaction failed.
I asked them about it, and they answered:
"Thia ia an issue with your economy plugin.
When a transaction succeeds, they set the error message in Vault as "Successful", which makes no sense.
They should instead leave it empty.
The solution is either to report it over them or switch to another economy plugin."
Please can you fix it somehow?
Maybe to add the new option in config.yml, like "empty-response-success-transaction: true|false"...
Thank you!

**Comment by HSGamer** [comment]
Why don't they just check the type of the response? Why checking the error message? It makes no sense.

**Comment by HSGamer** [comment]
I'm not gonna add that option to this plugin. They should be the one to fix it.
